# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 14:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0004_auto_20170417_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chapters',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='cut',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='wrongquestions',
            options={'managed': False},
        ),
    ]
