# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0005_auto_20170417_1430'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cut',
            table='cut',
        ),
        migrations.AlterModelTable(
            name='difficulty',
            table='difficulty',
        ),
        migrations.AlterModelTable(
            name='wrongquestions',
            table='wrong_questions',
        ),
    ]
