# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0009_auto_20170417_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cut',
            options={},
        ),
        migrations.AlterModelOptions(
            name='difficulty',
            options={},
        ),
    ]
