# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0013_auto_20170417_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='difficulty',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='cut',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wrongquestions',
            table=None,
        ),
    ]
