# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0015_auto_20170417_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapters',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modules',
            options={},
        ),
        migrations.AlterModelOptions(
            name='parts',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questions',
            options={},
        ),
        migrations.AlterField(
            model_name='difficulty',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='difficulty',
            table=None,
        ),
    ]
