# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0016_auto_20170417_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authgrouppermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authpermission',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authusergroups',
            options={},
        ),
        migrations.AlterModelOptions(
            name='authuseruserpermissions',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangoadminlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangocontenttype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='djangosession',
            options={},
        ),
        migrations.AlterModelTable(
            name='chapters',
            table=None,
        ),
        migrations.AlterModelTable(
            name='modules',
            table=None,
        ),
        migrations.AlterModelTable(
            name='parts',
            table=None,
        ),
        migrations.AlterModelTable(
            name='questions',
            table=None,
        ),
    ]
