# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0022_auto_20170417_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wrongquestions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
