# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-18 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER_login', '0023_auto_20170418_0314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wrongquestions',
            options={'managed': False},
        ),
    ]
